### ISSUE TITLE
Site not loading on Safari🐛 

### ISSUE THREAD

**Issue by cassgvp** [libscie/ResearchEquals.com#1020] opened 2022-12-22 14:16 UTC
### URL of the Page

https://www.researchequals.com

### What happened?

I’ve just tried to visit R= on safari and get the error below. Works fine on Chrome.
<img width="1440" alt="Screenshot 2022-12-22 at 14 14 52" src="https://user-images.githubusercontent.com/43407869/209153152-aabbf3f3-d6db-4aff-8bf4-357d740b1191.png">

### Steps to reproduce

visit https://www.researchequals.com

### What browser(s) did you use?

Safari

### Anything else?

Safari Version 13.1.3 running on Catalina Version 10.15.7.

**Comment by chartgerink** [comment] 2022-12-22 14:50
@all-contributors add @cassgvp for bug

**Comment by chartgerink** [comment] 2023-01-30 08:36
I'm marking this as blocked for now, because it's so hard to test this issue at the moment - we don' have direct access to a development machine to see where the issue lies.

If you are running Safari 13.1 and are able to are comfortable to do a debug session (using the terminal and a bit of coding to try some things out together), please let me know on ceo@libscie.org 🙌

**Comment by chartgerink** [comment] 2023-02-23 09:56
@cassgvp was so kind to help debug this issue 💜 

Together, we figured out the following:
1. The issue is only on the root page `/`! (not on dashboard, login, terms, etc)
2. It might've been the localization library (`t, useTranslation`) but after doing a quickfix to test this it didn't work #1149 

I went and checked [the market share](https://www.stetic.com/market-share/browser/) of the safari version and it appears to be <0.5% at this point.
<img width="1194" alt="Screenshot 2023-02-23 at 10 55 28" src="https://user-images.githubusercontent.com/2946344/220874381-434b9a9f-ec70-433a-acaa-ea716afb1736.png">

So, steps made - not fixed just yet!

**Comment by chartgerink** [comment] 2023-05-25 16:10
I'm closing this issue as this currently is not a priority to fix, and I don't want to create the impression we are committed to fixing it at this point. We don't have the resources to make a currently unknown fix for a browser version with such a small percentage of use at this point (also in our analytics 👇 )

<img width="554" alt="Screenshot 2023-05-25 at 18 08 53" src="https://github.com/libscie/ResearchEquals.com/assets/2946344/fdc862e8-efe2-41d7-a84f-4307eef37115">

I would like to be able to tackle *all* issues but we're at a stage that we simply can't. Big shoutout to @cassgvp for reporting and helping debug, I'm sorry I can't fix this right now.

**Closed by chartgerink** 2023-05-25 16:10 UTC
Labels: bug, wontfix, blocked
