### ISSUE TITLE
Edit profile modal showing as overlapped

### ISSUE THREAD

**Issue by nsunami** [libscie/ResearchEquals.com#572] opened 2022-08-03 23:38 UTC
When opening Edit Profile → Account Tab, the popup shows as if there are two modals overlapping with each other: 

<img width="610" alt="image" src="https://user-images.githubusercontent.com/17035406/182730242-1b956d99-0d8a-4fe9-82f5-2e6adcc201d1.png">

I'd expect something like this:

<img width="689" alt="image" src="https://user-images.githubusercontent.com/17035406/182730603-236f6ecf-33d2-48ab-9919-2c40b31e0a2b.png">

Edit:

I'm using Chrome 103.0.5060.134. The problem persists in Incognito Mode.

The problem happens on Firefox 102.0 (64-bit) too. 

The path is https://www.researchequals.com/nsunami

**Comment by chartgerink** [comment] 2022-08-04 06:53
I can't reproduce this in Firefox. Could you share a bit more information - e.g., what browser are you using? Anything specific that might be worth sharing to help understand what's happening?

**Comment by nsunami** [comment] 2022-08-04 23:29
I'm using Chrome. I tried it in the Incognito mode and the same bug persists..

**Comment by chartgerink** [comment] 2022-08-05 09:38
Thanks @nsunami!

🤔 i'm trying to reproduce in Chrome but unable to it seems

**Comment by chartgerink** [comment] 2022-08-10 08:41
I'm closing this issue as I cannot reproduce, and inspecting the code in `settings.tsx` also provides me with no reason to believe there is an issue in our code. 

Please feel free to reopen the issue if you see this happen and you can gather some more information on what might be happening (e.g., in the console log).

**Closed by chartgerink** 2022-08-10 08:41 UTC
Labels: bug
