### ISSUE TITLE
`npm run test` throws an error 

### ISSUE THREAD

**Issue by nsunami** [libscie/ResearchEquals.com#567] opened 2022-08-03 00:27 UTC
I was trying to push the remote, but I couldn't do so because the pre-push test was failing. 

It seems like the test is looking for `DATABASE_URL` in the `.env` file. But, I'm using `.env.local` file that's default for blitz.

```
  ● resetPassword mutation › works correctly


    Invalid `db.user.create()` invocation in
    /Users/nami/git/ResearchEquals.com/app/auth/mutations/resetPassword.test.ts:27:32

      24 const past = new Date()
      25 past.setHours(past.getHours() - 4)
      26 
    → 27 const user = await db.user.create(
      error: Environment variable not found: DATABASE_URL.
      -->  schema.prisma:6
       | 
     5 |   provider = "postgres"
     6 |   url      = env("DATABASE_URL")
       | 

```

Adding the `DATABASE_URL` environment variable to the `.env` file resolves the issue. But, I assumed the `.env` file is used for storing non-secrets for Blitz JS apps (and thus checked into the version control by default). 

I see that `.env` file is ignored since PR https://github.com/libscie/ResearchEquals.com/pull/553

@chartgerink What would be a good way to go? Should I just add `DATABASE_URL` to both `.env` and `.env.local` and go on?

**Comment by chartgerink** [comment] 2022-08-04 06:59
Have you tried copying your `.env.local` to `.env`? I think this would fix the issue.

I think ignoring the `.env` makes sense in the end, because people might end up accidentally committing their environment settings otherwise. We should indeed update the `README.md` as a result. 

Could you let me know whether this fixes your issues? I will also test on my end.

**Comment by nsunami** [comment] 2022-08-04 23:39
I see. I tried checking out the main branch, `npm install` and then `npm run test`—the problem persists for me.

Moving everything to `.env` works for testing and building the app.

**Comment by chartgerink** [comment] 2022-08-08 11:27
Could you try running it in a new copy of the repository elsewhere? I am wondering whether there is something in the setup that's causing a difference.

**Comment by nsunami** [comment] 2022-08-08 21:20
I tried:

1. Cloning the app fresh 
2. Creating `.env.local` and add env variables there
3. `npm install`
4. `npm run test`

Then get the same error that the env var for `DATABASE_URL` is not found.
```
      error: Environment variable not found: DATABASE_URL.
```

😕

**Comment by chartgerink** [comment] 2022-08-09 10:23
Thanks @nsunami! 🙏 I tried to do the same and I did not get an error. This suggest there may be something happening on your configuration. 

Some options to resolve:  
- Could you share how your `.env` and `.env.local` looks? (without the actual secrets!)
- Could you share output of `node -v` and `blitz -v`?
- Could you share output of `echo $DATABASE_URL`?
- Any other output that shows before you get the error?

**Comment by tefkah** [comment] 2022-08-11 12:18
I have similar issues, I think it's because Prisma seems to be only looking at `.env`

<img width="609" alt="image" src="https://user-images.githubusercontent.com/21983833/184131465-43c94763-d02d-47bb-84a9-298486261df6.png">

When doing this with the db url in `.env` (`.env.local`)
<img width="609" alt="image" src="https://user-images.githubusercontent.com/21983833/184131643-ad0297e2-3804-4b11-8ea7-2d03d3470d49.png">

**Comment by chartgerink** [comment] 2022-08-11 12:24
It seems like this only started occurring after the `.env` was being ignored - does unignoring it help?

Does running `blitz prisma migrate dev` work as expected? 
I keep asking to figure out how to fix, because I don't have this issue 😊

**Comment by tefkah** [comment] 2022-08-11 12:26
Yes!
<img width="981" alt="image" src="https://user-images.githubusercontent.com/21983833/184132918-cf209c64-6d7e-49f8-9a95-c4b278dde4f2.png">

**Comment by tefkah** [comment] 2022-08-11 13:42
Hmm, but that doesn't still doesnt fix the testing unfortunately, I was misled because the env vars are kept between runs for jest it seems, but after reloading the window prisma still complains.

**Comment by nsunami** [comment] 2022-08-11 22:03
@chartgerink Answering my questions below!

## Could you share how your `.env` and `.env.local` looks? (without the actual secrets!)

- `.env`: It's the Blitz default file:
```
# This env file should be checked into source control
# This is the place for default values for all environments
# Values in `.env.local` and `.env.production` will override these values
```

- `.env.local`: I have all the secrets there, including `DATABASE_URL`

## Could you share output of `node -v` and `blitz -v`?

`node -v`:
```
v18.4.0
```

`blitz -v`:
```
blitz: 0.45.4 (global)
blitz: 0.45.5 (local)
```


## Could you share output of `echo $DATABASE_URL`?

`echo $DATABASE_URL` → (nothing)

## Any other output that shows before you get the error?

Nothing special that I can think of. Below is the full error. I can see that `npm run test` is trying to pull env vars from `.env` and, which would not work (since my `.env` is empty). 

`Determining test suites to run...Loaded env from /Users/nami/git/ResearchEquals.com/.env`

<details>

```

> researchequals@1.0.0 test
> jest

Determining test suites to run...Loaded env from /Users/nami/git/ResearchEquals.com/.env
 FAIL   SERVER  app/auth/mutations/forgotPassword.test.ts
  ● forgotPassword mutation › does not throw error if user doesn't exist

    Failed: 1

      3 | import db from "db"
      4 |
    > 5 | beforeEach(async () => {
        | ^
      6 |   await db.$reset()
      7 | })
      8 |

      at Env.beforeEach (node_modules/jest-jasmine2/build/jasmineAsyncInstall.js:46:24)
      at Object.<anonymous> (app/auth/mutations/forgotPassword.test.ts:5:1)

  ● forgotPassword mutation › does not throw error if user doesn't exist

    expect(received).resolves.not.toThrow()

    Received promise rejected instead of resolved
    Rejected to value: [Error:·
    Invalid `db.user.findFirst()` invocation in
    /Users/nami/git/ResearchEquals.com/app/auth/mutations/forgotPassword.ts:10:30·
       7·
       8 export default resolver.pipe(resolver.zod(ForgotPassword), async ({ email }) => {
       9   // 1. Get the user
    → 10   const user = await db.user.findFirst(
      error: Environment variable not found: DATABASE_URL.
      -->  schema.prisma:6
       |·
     5 |   provider = "postgres"
     6 |   url      = env("DATABASE_URL")
       |··
    Validation Error Count: 1]

      15 | describe("forgotPassword mutation", () => {
      16 |   it("does not throw error if user doesn't exist", async () => {
    > 17 |     await expect(forgotPassword({ email: "no-user@email.com" }, {} as Ctx)).resolves.not.toThrow()
         |           ^
      18 |   })
      19 |
      20 |   // @TODO: currently skipping this test as it relies on postmark. However, postmark requires a work account to setup so pre-commit tests are failing

      at expect (node_modules/expect/build/index.js:134:15)
      at Object.<anonymous> (app/auth/mutations/forgotPassword.test.ts:17:11)

 FAIL   SERVER  app/auth/mutations/resetPassword.test.ts
  ● resetPassword mutation › works correctly

    Failed: 1

      3 | import { hash256, SecurePassword } from "blitz"
      4 |
    > 5 | beforeEach(async () => {
        | ^
      6 |   await db.$reset()
      7 | })
      8 |

      at Env.beforeEach (node_modules/jest-jasmine2/build/jasmineAsyncInstall.js:46:24)
      at Object.<anonymous> (app/auth/mutations/resetPassword.test.ts:5:1)

  ● resetPassword mutation › works correctly


    Invalid `db.user.create()` invocation in
    /Users/nami/git/ResearchEquals.com/app/auth/mutations/resetPassword.test.ts:27:32

      24 const past = new Date()
      25 past.setHours(past.getHours() - 4)
      26 
    → 27 const user = await db.user.create(
      error: Environment variable not found: DATABASE_URL.
      -->  schema.prisma:6
       | 
     5 |   provider = "postgres"
     6 |   url      = env("DATABASE_URL")
       | 

    Validation Error Count: 1

      25 |     past.setHours(past.getHours() - 4)
      26 |
    > 27 |     const user = await db.user.create({
         |                  ^
      28 |       data: {
      29 |         email: "user@example.com",
      30 |         role: "CUSTOMER",

      at RequestHandler.handleRequestError (node_modules/@prisma/client/runtime/index.js:28664:13)
      at PrismaClient._getDmmf (node_modules/@prisma/client/runtime/index.js:29740:23)
      at PrismaClient._executeRequest (node_modules/@prisma/client/runtime/index.js:29661:22)
      at consumer (node_modules/@prisma/client/runtime/index.js:29618:18)
      at PrismaClient._request (node_modules/@prisma/client/runtime/index.js:29639:16)
      at Object.<anonymous> (app/auth/mutations/resetPassword.test.ts:27:18)


Test Suites: 2 failed, 1 skipped, 2 of 3 total
Tests:       2 failed, 2 skipped, 4 total
Snapshots:   0 total
Time:        2.019 s
Ran all test suites in 2 projects.

```

</details>

**Comment by chartgerink** [comment] 2022-08-12 08:03
Thanks for the details @nsunami and the comment @tefkah.

@tefkah could you check your `node -v`? I see @nsunami is running `v18.x.x` which may be causing it as I run `v16.x.x`. I wonder what version you're running.

FWIW @nsunami - if your `.env.` is empty Blitz will go to `.env.local` usually, so I am not sure why it's not picking this up. Could you try removing `.env` from `.gitignore` as well? Or try with `node v16.x.x` if you have `nvm` installed?

**Comment by tefkah** [comment] 2022-08-12 11:50
I have `v16.14.2`!

**Comment by nsunami** [comment] 2022-08-17 12:54
@chartgerink 

I tried:
1. Removing `.env` from `.gitgnore`, and  
2. Using node `v16.14.0`

But both resulted in the same `Environment variable not found: DATABASE_URL.` issue for me 😞

**Comment by chartgerink** [comment] 2022-08-22 12:51
Then I don't know how to fix this bug - it's hard to debug without being able to reproduce it 😅 

There is a suboptimal fix (`cp .env.local .env`) so I will close this issue. If anybody has future insights, feel free to post them here nonetheless! :-)

**Closed** 2022-09-08 07:12 UTC
Labels: bug, Maintenance
